server:
  port: 8061

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8060/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
urls:
  auth-url: http://localhost:8062/validate/token
  token-url: http://localhost:8062/oauth/token     

spring:
  application:
    name: account-service
  
management:
  security:
    enabled: false

logging:
  level:
    com.account: DEBUG
    